base_user/urls.py
from django.conf.urls import url

from .views import *

app_name = 'base-user'
urlpatterns = [
	url(r'^callback/$', callback, name='callback'),
	url(r'^redirect/$', redirect, name='redirect'),
	url(r'^logout/$', log_out, name='logout'),
]

panel/urls.py
from django.conf.urls import url

from .views import *

app_name = 'userprofile'
urlpatterns = [
	url(r'^$', index, name='index'),


	url(r'^user/list/$', user_list, name='user-list'),
	url(r'^user/list/removed/$', user_list_removed, name='user-list-removed'),
	url(r'^user/create/', user_create, name='user-create'),
	url(r'^user/edit/(?P<id>[0-9]+)/', user_edit, name='user-edit'),
	url(r'^user/remove/(?P<id>[0-9]+)/', user_remove, name='user-remove'),

	url(r'^avatar/list/$', avatar_list, name='avatar-list'),
	url(r'^avatar/create/', avatar_create, name='avatar-create'),
	url(r'^avatar/edit/(?P<id>[0-9]+)/', avatar_edit, name='avatar-edit'),
	url(r'^avatar/remove/(?P<id>[0-9]+)/', avatar_remove, name='avatar-remove'),

	url(r'^avatar-item/list/$', avatar_item_list, name='avatar-item-list'),
	url(r'^avatar-item/create/', avatar_item_create, name='avatar-item-create'),
	url(r'^avatar-item/edit/(?P<id>[0-9]+)/', avatar_item_edit, name='avatar-item-edit'),
	url(r'^avatar-item/remove/(?P<id>[0-9]+)/', avatar_item_remove, name='avatar-item-remove'),


	url(r'^test/$', test, name='test'),
	url(r'^main/settings/$', main_settings, name='main-settings'),


]

tbgm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
# from home.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^telegrambot/', include('telegrambot.urls', namespace="telegrambot")),
    url(r'^bot-api/', include('bot_app.urls', namespace='bot-app')),



    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
# urlpatterns += [

    url(r'^set-language/$', core_views.set_language, name='set_language'),
    url(r'^admin/', admin.site.urls, name="admin"),

    url(r'^', include('panel.urls', namespace='panel')),
    url(r'^accounts/', include('base_user.urls', namespace='base-user')),
)
# ]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

templates/base-main.html
{% load static %}
{% load  i18n %}
<!DOCTYPE html>
<html lang="en">


<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'local/vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'local/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->

  <link rel="stylesheet" href="{% static 'local/vendors/select2/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'local/vendors/select2-bootstrap-theme/select2-bootstrap.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'local/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'local/images/favicon.png' %}" />

  <link rel="stylesheet" href="{% static 'local/vendors/jsgrid/jsgrid.min.css' %}">
  <link rel="stylesheet" href="{% static 'local/vendors/jsgrid/jsgrid-theme.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">
<style>
    .jsgrid-grid-body .jsgrid-cell:first-child  , .jsgrid-row .jsgrid-cell:first-child {
        border-left: none;
        border-left: 1px solid #ccc;
    }
    .jsgrid-grid-body .jsgrid-cell {
        border-bottom: 1px solid #ccc;
        border-right: 1px solid #ccc;
    }
</style>
    {% block css_block %}

    {% endblock %}

</head>

<body class="sidebar-dark">
  <div class="container-scroller">
    <!-- partial:../../partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="{% url 'userprofile:index' %}"><img src="{% if base_main_settings and base_main_settings.big_logo %}{{ base_main_settings.big_logo.url }}{% else %}{% static 'local/images/big-logo.png' %}{% endif %}" class="mr-2" alt="logo"/></a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'userprofile:index' %}"><img src="{% if base_main_settings and base_main_settings.small_logo %}{{ base_main_settings.small_logo.url }}{% else %}{% static 'local/images/small-logo.png' %}{% endif %}" alt="logo"/></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="ti-layout-grid2"></span>
        </button>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="{% if base_profile.photo_url %}{{ base_profile.photo_url }}{% else %}{% static 'local/images/default-user.png' %}{% endif %}" alt="profile"/>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item" href="{% url 'panel:index' %}">
                <i class="ti-home text-primary"></i>
                {% trans 'Site' %}
              </a>
              <a class="dropdown-item" href="{% url 'panel:main-settings' %}">
                <i class="ti-settings text-primary"></i>
                {% trans 'Settings' %}
              </a>
              <a class="dropdown-item" href="{% url 'base-user:logout' %}">
                <i class="ti-power-off text-primary"></i>
                {% trans 'Logout' %}
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="ti-layout-grid2"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:../../partials/_sidebar.html -->
        {% with base_user_rules=base_profile.get_user_rules %}

            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    {% if base_profile.usertype == 1 or 'dashboard' in base_user_rules %}
                      <li data-field-id="ui-dashboard" class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:index' %}">
                          <i class="ti-home menu-icon"></i>
                          <span class="menu-title">{% trans 'Dashboard' %}</span>
                        </a>
                      </li>
                    {% endif %}
                    {% if base_profile.usertype == 1 or 'user-list' in base_user_rules or 'user-create' in base_user_rules or 'user-list-removed' in base_user_rules %}
                      <li class="nav-item" >
                        <a class="nav-link" data-toggle="collapse" href="#ui-users" aria-expanded="false" aria-controls="ui-basic">
                          <i class="ti-user menu-icon"></i>
                          <span class="menu-title">{% trans 'Users' %}</span>
                          <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-users">
                          <ul class="nav flex-column sub-menu">
                            {% if base_profile.usertype == 1 or 'user-list' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:user-list' %}">{% trans 'List' %}</a></li>
                            {% endif %}
                            {% if base_profile.usertype == 1 or 'user-create' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:user-create' %}">{% trans 'Create' %}</a></li>
                            {% endif %}
                            {% if base_profile.usertype == 1 or 'user-list-removed' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:user-list-removed' %}">{% trans 'Removed list' %}</a></li>
                            {% endif %}
                          </ul>
                        </div>
                      </li>
                    {% endif %}
                    {% if base_profile.usertype == 1 or 'avatar-list' in base_user_rules or 'avatar-create' in base_user_rules or 'avatar-list-removed' in base_user_rules %}
                      <li class="nav-item" >
                        <a class="nav-link" data-toggle="collapse" href="#ui-avatars" aria-expanded="false" aria-controls="ui-basic">
                          <i class="ti-face-smile menu-icon"></i>
                          <span class="menu-title">{% trans 'Avatars' %}</span>
                          <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-avatars">
                          <ul class="nav flex-column sub-menu">
                            {% if base_profile.usertype == 1 or 'avatar-list' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:avatar-list' %}">{% trans 'List' %}</a></li>
                            {% endif %}
                            {% if base_profile.usertype == 1 or 'avatar-create' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:avatar-create' %}">{% trans 'Create' %}</a></li>
                            {% endif %}
                          </ul>
                        </div>
                      </li>
                    {% endif %}
                    {% if base_profile.usertype == 1 or 'avatar-item-list' in base_user_rules or 'avatar-item-create' in base_user_rules or 'avatar-item-list-removed' in base_user_rules %}
                      <li class="nav-item" >
                        <a class="nav-link" data-toggle="collapse" href="#ui-avatar-items" aria-expanded="false" aria-controls="ui-avatar-items">
                          <i class="ti-paint-bucket menu-icon"></i>
                          <span class="menu-title">{% trans 'Avatar items' %}</span>
                          <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-avatar-items">
                          <ul class="nav flex-column sub-menu">
                            {% if base_profile.usertype == 1 or 'avatar-item-list' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:avatar-item-list' %}">{% trans 'List' %}</a></li>
                            {% endif %}
                            {% if base_profile.usertype == 1 or 'avatar-item-create' in base_user_rules %}
                                <li class="nav-item"> <a class="nav-link" href="{% url 'panel:avatar-item-create' %}">{% trans 'Create' %}</a></li>
                            {% endif %}
                          </ul>
                        </div>
                      </li>
                    {% endif %}
                  {% if base_profile.usertype == 1 or 'main-settings' in base_user_rules %}
                      <li class="nav-item" data-field-id="ui-main-settings">
                        <a class="nav-link" href="{% url 'userprofile:main-settings' %}" aria-controls="ui-main-settings">
                          <i class="ti-settings  menu-icon"></i>
                          <span class="menu-title">{% trans 'Main settings' %}</span>
                        </a>
                      </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'base-user:logout' %}" aria-controls="ui-main-settings">
                      <i class="ti-power-off menu-icon"></i>
                      <span class="menu-title">{% trans 'Logout' %}</span>
                    </a>
                  </li>
                </ul>
            </nav>

        {% endwith %}
      <!-- partial -->
      <div class="main-panel">

        {% block content_block %}

        {% endblock %}

        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">{% trans 'Copyright © All rights reserved' %} {{ now.year }}.</span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'local/vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'local/js/off-canvas.js' %}"></script>
  <script src="{% static 'local/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'local/js/template.js' %}"></script>
  <script src="{% static 'local/js/settings.js' %}"></script>
  <script src="{% static 'local/js/todolist.js' %}"></script>
  <!-- endinject -->
      <script>
        function activeMenu($class){
            $( "li[data-field-id='" + $class + "']" ).addClass('active');
            $( "a[href='#" + $class + "']" ).attr('aria-expanded','true');
            $('#'+$class).addClass('show')
        }
    </script>

<script src="{% static 'local/vendors/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'local/vendors/jquery.avgrund/jquery.avgrund.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
  <!-- Custom js for this page-->
  {% block js_block %}

  {% endblock %}
  <!-- End custom js for this page-->
</body>


</html>