panel/urls.py
from django.conf.urls import url

from .views import *

app_name = 'userprofile'
urlpatterns = [
	url(r'^$', index, name='index'),


	url(r'^user/list/$', user_list, name='user-list'),
	url(r'^user/list/removed/$', user_list_removed, name='user-list-removed'),
	url(r'^user/create/', user_create, name='user-create'),
	url(r'^user/edit/(?P<id>[0-9]+)/', user_edit, name='user-edit'),
	url(r'^user/remove/(?P<id>[0-9]+)/', user_remove, name='user-remove'),

	url(r'^avatar/list/$', avatar_list, name='avatar-list'),
	url(r'^avatar/create/', avatar_create, name='avatar-create'),
	url(r'^avatar/edit/(?P<id>[0-9]+)/', avatar_edit, name='avatar-edit'),
	url(r'^avatar/remove/(?P<id>[0-9]+)/', avatar_remove, name='avatar-remove'),

	url(r'^avatar-item/list/$', avatar_item_list, name='avatar-item-list'),
	url(r'^avatar-item/create/', avatar_item_create, name='avatar-item-create'),
	url(r'^avatar-item/edit/(?P<id>[0-9]+)/', avatar_item_edit, name='avatar-item-edit'),
	url(r'^avatar-item/remove/(?P<id>[0-9]+)/', avatar_item_remove, name='avatar-item-remove'),


	url(r'^test/$', test, name='test'),
	url(r'^main/settings/$', main_settings, name='main-settings'),


]

tbgm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
# from home.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^telegrambot/', include('telegrambot.urls', namespace="telegrambot")),
    url(r'^bot-api/', include('bot_app.urls', namespace='bot-app')),



    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
# urlpatterns += [

    url(r'^set-language/$', core_views.set_language, name='set_language'),
    url(r'^admin/', admin.site.urls, name="admin"),

    url(r'^', include('panel.urls', namespace='panel')),
    url(r'^accounts/', include('base_user.urls', namespace='base-user')),
)
# ]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

templates/panel/avatars/include/list-item.html
{% load static %}
<tr id="list-item-{{ data_item.id }}">
    <td>{{ for_i }}</td>
    <td>{{ data_item.title }}</td>
    <td>{{ data_item.gender }}</td>
    <td>{{ data_item.status }}</td>
    <td>
        <a data-fancybox="gallery" href="{% if data_item.photo %}{{ data_item.photo.url }}{% else %}{% static 'local/images/default-user.png' %}{% endif %}">
            {% if data_item.photo %} <img alt="{{ data_item.title }}" src="{{ data_item.photo.url }}" style="max-height: 50px;width: auto;"/> {% else %} <img alt="{{ data_item.title }}" src="{% static 'local/images/default-user.png' %}" style="max-height: 50px;width: auto;"/>{% endif %}
        </a>
        </td>
    <td>{{ data_item.date|date:'d.m.Y H:i' }}</td>
    <td>
        <a style=""  href="{% url 'panel:avatar-edit' data_item.id %}" class="btn btn-icon btn-square btn-warning">
             <i class="ti-pencil-alt"></i>
        </a>
        <a style="" href="javascript:void(0)" onclick="deleteDataItem('{% url 'panel:avatar-remove' data_item.id %}',{{ data_item.id }})" class="btn btn-icon btn-square btn-danger">
            <i class="ti-close"></i>
        </a>
    </td>
</tr>

templates/panel/avatars/include/main.html
{% load static %}{% load i18n %}





<div class="table-responsive" style="height: 442px;">
    <table class="table table-bordered">
        <thead class="">
            <tr class="">
                <th class="jsgrid-header-cell" >n</th>
                <th class="jsgrid-header-cell" >{% trans 'Title' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Gender' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Status' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Photo' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Date' %}</th>
                <th class="jsgrid-header-cell" >/</th>
            </tr>
        </thead>
        <tbody id="">
            {% autoescape off %}
            {{ list_html }}
            {% endautoescape %}
        </tbody>
    </table>
</div>\